### ISSUE TITLE
SEO issues with website

### ISSUE THREAD

**Issue by augbog** [masayuki0812/c3js.org#33]
Right now c3js.org doesn't have a `<meta name="description">` so when Google crawls the page, it determines it on its own. This leads to a lot numbers spilling through into the description which isn't very useful for the user.

![screen shot 2015-06-03 at 4 39 26 pm](https://cloud.githubusercontent.com/assets/2054339/7973850/37a77358-0a0f-11e5-901c-bff8410bafae.png)

**Comment by aendrew** [comment]
Yikes, this should be fixed...

**Comment by kas** [comment]
Wanted to mention that this still occurs when I search "c3js". This does not occur when I search only "c3".

**Comment by kt3k** [comment]
Now index.html has `<meta content='D3 based reusable chart library' name='description'>`, but this is still an issue.

**Comment by augbog** [comment]
It's possible you may need to ask Google to [refetch your site's meta information via the Search console](https://support.google.com/webmasters/answer/6065812?hl=en) because it caches its search results.
